### ISSUE TITLE
Erroneous and misleading Statement in Ethereum Transaction Fees on  votings/proposal number pages

### ISSUE THREAD

**Issue by dancankimutai** [api3dao/api3-tracker#64] opened 2023-04-08 12:43 UTC
The amount spent in fees in ( https://tracker.api3.org/votings/132)  shows an absurd amount of Eth was spent on fees which should not be the case .It says:

_Spent 1,261,642 ETH in fees, Est $58.01_ 

1,261,642 ETH at current 1868usd per eth is $2,357,270,837.43 USD in fees which ain't true.

The 1,261,642 here comes from addition of the gas fees used by the various users in the said proposal, this should have been denoted as 1,261,642 gas in fees , Est $58.01 or write the sum of the ETH amounts used in the proposal and the estimated fee.

## Steps to reproduce

1. Go to the Proposals tab of the API3 DAO Tracker and click on any of the items on the (Lets explain using this as an example https://tracker.api3.org/votings/132) 

2. Just under the votes it says _At the time of the proposal DAO had 41,468,139 shares staked, 6,220,220 shares are required for this proposal to be accepted
Spent 1,261,642 ETH in fees, Est $58.01_(Shown in the 2nd screenshot)

3. 1,261,642 ETH at current 1868usd per eth is $2,357,270,837.43 USD in fees.

## Expected behavior
The amount of ETH fees must equal the estimated fee when converted.It can also be denoted using the word (gas units) to avoid confusion e.g Spent 1,261,642 gas units in fees , Est $58.01  .It can also be written with the sum of ETH fee amounts used instead of gas units e.g Spent 0.0064 ETH in fees, Est $12.01

## Current behavior

Error in Ethereum Transaction Fee representation that can cause confusion or mislead users.

## Screenshots (if applicable)
![Screenshot from 2023-04-08 15-30-05](https://user-images.githubusercontent.com/59916500/230721157-463356ec-475b-4eac-a450-63ecdd2092a9.png)
![Screenshot from 2023-04-08 15-31-04](https://user-images.githubusercontent.com/59916500/230721181-2f738668-546d-4461-9834-389d81fe0cec.png)

## Environment

Os: Kali linux.
Browser : Firefox.

## Potential consequences

It can mislead users about the actual amount of fees they are being charged for Ethereum transactions. This can cause confusion and mistrust in the website or application, leading to a loss of reputation and potential loss of business.

**Comment by Ashar2shahid** [comment] 2023-04-11 14:58
This is a duplicate of #59 and #51 but thank you for taking the time to submit

**Closed by Ashar2shahid** 2023-04-11 14:58 UTC
Labels: cbb
