### ISSUE TITLE
"ETH Spent in fees" inconsistent between Proposals Overview Page & each item's individual listing page.

### ISSUE THREAD

**Issue by Tubbsyy** [api3dao/api3-tracker#59] opened 2023-03-25 21:11 UTC
The “ETH spent in fees” on the API DAO Proposals **OVERVIEW** tab on each item does not match up with the “ETH spent in fees” on the actual page for each item. This appears to be a result of using separate methods to try to calculate the place of the decimal across two pages. Please reference the full details below for further information.

## Steps to reproduce

_1. Go to the **Proposals tab** of the API3 DAO Tracker (or visit the link: [https://tracker.api3.org/votings](https://tracker.api3.org/votings) ) and look at any of the items on the page. For example, look at the first screenshot down below. Or, if you’re on the page, look at the first 2 **************PENDING************** proposals._

_2. In the first proposal (API Provider Partnerships for managed dAPIs April 2023 - June 2023), it says **spent: 0.0453191 ETH in fees, estimating $14.60**). **Click on the proposal.**_

_3. After clicking on the same proposal (Pending proposal number 1, shown in the first screenshot below for reference), you will notice that it says **“Spent 453,191 ETH in fees, Est $14.6”**)._

_4. Seeing this error, the next step is to go into the repo to determine where the problem is. I took a look at it and it appears to be line 108 on components/VotingSummary.tsx which has this line:_
_```{toCurrency(props.totalGasUsed)}```_

_5. If we compare the code on the proposals page of the website, it uses a different method to calculate the number, giving it the proper decimal places. You can see the method used for this in the components/VotingsList.tsx on **line 76**:_
_```{withDecimals(props.totalGasUsed + "", 7)}```_

I think this is the correct method, otherwise if not, the bug is still present and I wanted to report this to help improve it! Notice how the first code snippet from VotingSummary.tsx uses the toCurrency function instead of the withDecimals function? I think this will solve it.

## Expected behavior

_Expected consistency between the proposal overview page and the individual proposal pages to have the same correct “spent” amount._

## Current behavior

_The “ETH spent in fees” on the API3 DAO Proposals tab for each item does not match the “ETH spent in fees” on the actual page for each item._

## Screenshots (if applicable)

![API3-DAO-Proposals](https://user-images.githubusercontent.com/90659745/227741886-36f56049-e63a-4544-b9bc-e5737a9452da.png)

![API3-DAO-Proposal-Details](https://user-images.githubusercontent.com/90659745/227741895-daf1e034-e3a3-46f4-8447-c2a457b05ea3.png)

## Environment

_Windows 10 64-bit.  Google Chrome 111.0.5563.65 (64 bit)_

## Potential consequences

_Users could be misled on how much ETH was actually spent, which can create a lack of trust in results._

**Comment by Ashar2shahid** [comment] 2023-04-11 14:50
@Tubbsyy thank you for taking the time to submit the bug report, this seems like a duplicate of [this] issue but you this has more detailed information about the bug so we can discuss the bounty in discord. Can you add me there? discord username is L_Alive#4594

**Closed** 2023-04-11 14:52 UTC
Labels: duplicate, cbb
