### ISSUE TITLE
shows incorrect data

### ISSUE THREAD

**Issue by Marcok-99** [api3dao/api3-tracker#82] opened 2023-07-24 16:20 UTC
Some voted for this proposal. But the amount is not visible. 
It was visible bevor i voted against the proposal. 

https://tracker.api3.org/votings/15
<img width="1470" alt="Bildschirmfoto 2023-07-24 um 18 14 24" src="https://github.com/api3dao/api3-tracker/assets/39245842/1af3e8f4-4599-49e9-83c9-0e5615de651c">

**Comment by dcroote** [comment] 2023-07-25 05:50
Duplicate of https://github.com/api3dao/api3-tracker/issues/52

**Closed** 2023-08-14 05:59 UTC
